In [1]:
import numpy as np

# Do actual matrix matrix multiplication

In [2]:
def debug_mm():
    matA = np.zeros((12, 12))
    matB = np.zeros((12, 12))
    for i in range(matA.shape[0]):
        for j in range(matA.shape[1]):
            matA[i, j] = abs(i+j)
            matB[i, j] = abs(i-j)

    matC = np.ones((12, 12))
    prod = np.matmul(matA, matB)

    matC = np.add(matC, prod)
    print('\nmatC += matA * matB')
    print(matC)
    
    return matC
    
soln = debug_mm()


matC += matA * matB
[[ 507.  441.  377.  317.  263.  217.  181.  157.  147.  153.  177.  221.]
 [ 573.  497.  425.  359.  301.  253.  217.  195.  189.  201.  233.  287.]
 [ 639.  553.  473.  401.  339.  289.  253.  233.  231.  249.  289.  353.]
 [ 705.  609.  521.  443.  377.  325.  289.  271.  273.  297.  345.  419.]
 [ 771.  665.  569.  485.  415.  361.  325.  309.  315.  345.  401.  485.]
 [ 837.  721.  617.  527.  453.  397.  361.  347.  357.  393.  457.  551.]
 [ 903.  777.  665.  569.  491.  433.  397.  385.  399.  441.  513.  617.]
 [ 969.  833.  713.  611.  529.  469.  433.  423.  441.  489.  569.  683.]
 [1035.  889.  761.  653.  567.  505.  469.  461.  483.  537.  625.  749.]
 [1101.  945.  809.  695.  605.  541.  505.  499.  525.  585.  681.  815.]
 [1167. 1001.  857.  737.  643.  577.  541.  537.  567.  633.  737.  881.]
 [1233. 1057.  905.  779.  681.  613.  577.  575.  609.  681.  793.  947.]]


# Do the round robin matrix multiplication

In [3]:
matA_1 = np.zeros((12, 4))
matB_1 = np.zeros((4, 12))
for i in range(matA_1.shape[0]):
    for j in range(matA_1.shape[1]):
        matA_1[i, j] = abs(i+j)
        matB_1[j, i] = abs(i-j)

matC_1 = np.ones((12, 12))

In [4]:
matA_2 = np.zeros((12, 4))
matB_2 = np.zeros((4, 12))
for i in range(matA_2.shape[0]):
    for j in range(matA_2.shape[1]):
        matA_2[i, j] = abs(i+j+4)
        matB_2[j, i] = abs(i-j-4)

matC_2 = np.zeros((12, 12))

In [5]:
matA_3 = np.zeros((12, 4))
matB_3 = np.zeros((4, 12))
for i in range(matA_3.shape[0]):
    for j in range(matA_3.shape[1]):
        matA_3[i, j] = abs(i+j+8)
        matB_3[j, i] = abs(i-j-8)

matC_3 = np.zeros((12, 12))

In [6]:
def partial_solve(A, B, C):
    for i in range(4):
        for j in range(12):
            for k in range(12):
                C[j, k] += A[j, i]*B[i, k]

In [7]:
partial_solve(matA_1, matB_1, matC_1)
print(matC_1)

[[ 15.   9.   5.   5.  11.  17.  23.  29.  35.  41.  47.  53.]
 [ 21.  13.   9.  11.  21.  31.  41.  51.  61.  71.  81.  91.]
 [ 27.  17.  13.  17.  31.  45.  59.  73.  87. 101. 115. 129.]
 [ 33.  21.  17.  23.  41.  59.  77.  95. 113. 131. 149. 167.]
 [ 39.  25.  21.  29.  51.  73.  95. 117. 139. 161. 183. 205.]
 [ 45.  29.  25.  35.  61.  87. 113. 139. 165. 191. 217. 243.]
 [ 51.  33.  29.  41.  71. 101. 131. 161. 191. 221. 251. 281.]
 [ 57.  37.  33.  47.  81. 115. 149. 183. 217. 251. 285. 319.]
 [ 63.  41.  37.  53.  91. 129. 167. 205. 243. 281. 319. 357.]
 [ 69.  45.  41.  59. 101. 143. 185. 227. 269. 311. 353. 395.]
 [ 75.  49.  45.  65. 111. 157. 203. 249. 295. 341. 387. 433.]
 [ 81.  53.  49.  71. 121. 171. 221. 271. 321. 371. 421. 471.]]


In [8]:
partial_solve(matA_2, matB_2, matC_2)
print(matC_2)

[[126. 104.  82.  60.  38.  24.  20.  28.  50.  72.  94. 116.]
 [148. 122.  96.  70.  44.  28.  24.  34.  60.  86. 112. 138.]
 [170. 140. 110.  80.  50.  32.  28.  40.  70. 100. 130. 160.]
 [192. 158. 124.  90.  56.  36.  32.  46.  80. 114. 148. 182.]
 [214. 176. 138. 100.  62.  40.  36.  52.  90. 128. 166. 204.]
 [236. 194. 152. 110.  68.  44.  40.  58. 100. 142. 184. 226.]
 [258. 212. 166. 120.  74.  48.  44.  64. 110. 156. 202. 248.]
 [280. 230. 180. 130.  80.  52.  48.  70. 120. 170. 220. 270.]
 [302. 248. 194. 140.  86.  56.  52.  76. 130. 184. 238. 292.]
 [324. 266. 208. 150.  92.  60.  56.  82. 140. 198. 256. 314.]
 [346. 284. 222. 160.  98.  64.  60.  88. 150. 212. 274. 336.]
 [368. 302. 236. 170. 104.  68.  64.  94. 160. 226. 292. 358.]]


In [9]:
partial_solve(matA_3, matB_3, matC_3)
print(matC_3)

[[366. 328. 290. 252. 214. 176. 138. 100.  62.  40.  36.  52.]
 [404. 362. 320. 278. 236. 194. 152. 110.  68.  44.  40.  58.]
 [442. 396. 350. 304. 258. 212. 166. 120.  74.  48.  44.  64.]
 [480. 430. 380. 330. 280. 230. 180. 130.  80.  52.  48.  70.]
 [518. 464. 410. 356. 302. 248. 194. 140.  86.  56.  52.  76.]
 [556. 498. 440. 382. 324. 266. 208. 150.  92.  60.  56.  82.]
 [594. 532. 470. 408. 346. 284. 222. 160.  98.  64.  60.  88.]
 [632. 566. 500. 434. 368. 302. 236. 170. 104.  68.  64.  94.]
 [670. 600. 530. 460. 390. 320. 250. 180. 110.  72.  68. 100.]
 [708. 634. 560. 486. 412. 338. 264. 190. 116.  76.  72. 106.]
 [746. 668. 590. 512. 434. 356. 278. 200. 122.  80.  76. 112.]
 [784. 702. 620. 538. 456. 374. 292. 210. 128.  84.  80. 118.]]


In [10]:
res = matC_1 + matC_2 + matC_3
print(res)

[[ 507.  441.  377.  317.  263.  217.  181.  157.  147.  153.  177.  221.]
 [ 573.  497.  425.  359.  301.  253.  217.  195.  189.  201.  233.  287.]
 [ 639.  553.  473.  401.  339.  289.  253.  233.  231.  249.  289.  353.]
 [ 705.  609.  521.  443.  377.  325.  289.  271.  273.  297.  345.  419.]
 [ 771.  665.  569.  485.  415.  361.  325.  309.  315.  345.  401.  485.]
 [ 837.  721.  617.  527.  453.  397.  361.  347.  357.  393.  457.  551.]
 [ 903.  777.  665.  569.  491.  433.  397.  385.  399.  441.  513.  617.]
 [ 969.  833.  713.  611.  529.  469.  433.  423.  441.  489.  569.  683.]
 [1035.  889.  761.  653.  567.  505.  469.  461.  483.  537.  625.  749.]
 [1101.  945.  809.  695.  605.  541.  505.  499.  525.  585.  681.  815.]
 [1167. 1001.  857.  737.  643.  577.  541.  537.  567.  633.  737.  881.]
 [1233. 1057.  905.  779.  681.  613.  577.  575.  609.  681.  793.  947.]]


In [11]:
(res == soln).all()

True